import Head from 'next/head';
import SidebarComponent from '@/components/Sidebar';

export default function Home() {
  return (
    <>
      <Head>
        <title>Next & Tailwind Sidebar</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <SidebarComponent />
      </main>
    </>
  );
}
